OPENAI_API_KEY="${OPENAI_API_KEY}"

# Default http://localhost:11434
OLLAMA_BASE_URL="http://localhost:11434"
# Default  llama3.2:3b
CODER_MODEL="qwen2.5-coder:7b"
# Default  llama3.2:3b
AGENT_MODEL="qwen3:8b"